// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections;
using System.Collections.Generic; 
using System.IO;
using System.Linq;

using Foundation;
using UIKit;
using CoreGraphics;
using CoreFoundation;
using AudioToolbox;

namespace SecurePDF
{

	/* List of bugs: 
	 * pdf drawing feature, printing feature, sharing feature needs to be addded into the pdf reader  
	 * The files need to be encrypted via AES-256
	 * User needs to be able to delete any of the files inside the library
	 * needs to auatomctcially retireve files from adobe reader if the user allows it 
	*/
	public partial class LibraryControllerTable : UITableViewController
	{
		public LibraryControllerTable (IntPtr handle) : base (handle)
		{
		}

		public LibraryControllerTable(){}

		public List<string> pdfList = new List<string>(){};
		public List<string> creationDate = new List<string>() { };
		public List<string> size = new List<string>() { };
		List<int> selectedCellsToRemove = new List<int>() { };

		List<int> corruptIndex = new List<int>() { };

		UIView emptyPDF = new UIView();
		UIImageView emptyImage = new UIImageView();
		UILabel description = new UILabel();
		UILabel description_2 = new UILabel();
		UILabel titleDescription = new UILabel();

		public List<UIImage> thumbnailImage = new List<UIImage>() { };
		UISearchController searchController = new UISearchController();
		UISearchBar search = new UISearchBar();
		public PDFReader pdfRead = new PDFReader();
		public AppDelegate appDelegate {
			get {
				return (AppDelegate)UIApplication.SharedApplication.Delegate; 
			}
		}

		public override void ViewWillLayoutSubviews()
		{
			if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeLeft || UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeRight)
			{
				this.emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				this.emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.Y - 200.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Bounds.Left + 35.0f, this.View.Center.Y + 10.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Bounds.Left + 35.0f, this.View.Center.Y + 70.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
				this.titleDescription.Frame = new CGRect(this.View.Center.X - 60.0f, this.View.Center.Y - 200.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}
			else if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.Portrait || UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.PortraitUpsideDown)
			{
				this.emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				this.emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.X - 95.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Bounds.Left + 5.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Bounds.Left + 5.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
				this.titleDescription.Frame = new CGRect(this.View.Center.X - 60.0f, this.View.Center.Y - 260.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}


		}

		public override void ViewDidAppear(bool animated)
		{
			Console.WriteLine("Search table Value: " + this.appDelegate.tablePDFSearch);
			this.NavigationController.SetToolbarHidden(true, true);

			if (this.appDelegate.tablePDFSearch == 1)
			{
				Console.WriteLine("Search selected");
				this.TableView.ScrollToRow(this.appDelegate.selectedIndexPDF, UITableViewScrollPosition.Top, true);
				this.TableView.SelectRow(this.appDelegate.selectedIndexPDF, true, UITableViewScrollPosition.Top);
				//	Console.WriteLine("Search selected");
			}
		}

		private void addImageContext(string[] directory, int i) {
			Console.WriteLine("i: " + i);
			try
			{
				CGPDFDocument pdfToLoad = CGPDFDocument.FromFile(directory[i]);
				if (pdfToLoad == null)
				{
					throw new NullReferenceException();
				}
				else {
					var firstPage = pdfToLoad.GetPage(1);
					var width = 240.0f;
					var pageRect = firstPage.GetBoxRect(CGPDFBox.Media);


					var pdfScale = width / pageRect.Size.Width;

					pageRect.Size = new CGSize(pageRect.Size.Width * pdfScale, pageRect.Size.Height * pdfScale);
					pageRect.X = 0;
					pageRect.Y = 0;
					UIGraphics.BeginImageContext(pageRect.Size);

					var context = UIGraphics.GetCurrentContext();

					context.SetFillColor(1.0f, 1.0f, 1.0f, 1.0f);
					context.FillRect(pageRect);
					context.SaveState();
					context.TranslateCTM(0.0f, pageRect.Size.Height);
					context.ScaleCTM(1.0f, -1.0f);
					context.ConcatCTM(firstPage.GetDrawingTransform(CGPDFBox.Media, pageRect, 0, true));
					context.DrawPDFPage(firstPage);
					context.RestoreState();

					UIImage thm = UIGraphics.GetImageFromCurrentImageContext();

					UIGraphics.EndImageContext();
					this.thumbnailImage.Add(thm);
				}
			}
			catch(NullReferenceException) {
				UIImage nullImage = new UIImage();
				this.corruptIndex.Add(i);
				this.thumbnailImage.Add(nullImage);
			}
		}

		public override void ViewDidLoad()
		{
			this.NavigationController.NavigationBar.BackgroundColor = UIColor.White;
			this.NavigationItem.Title = "My PDFs";
			this.TableView.RowHeight = 70.0f;
			this.appDelegate.library = this;
			this.appDelegate.resultsStringPDF = this.pdfList;
			UIStoryboard story = UIStoryboard.FromName("Main", NSBundle.MainBundle);
			this.appDelegate.PDF = story.InstantiateViewController("PDFReader") as PDFReader;

			this.searchController = new UISearchController(new resultsController());
			this.searchController.SearchResultsUpdater = new searchUpdator(this);
			this.searchController.DimsBackgroundDuringPresentation = true;
			this.searchController.HidesNavigationBarDuringPresentation = true;

			this.search = this.searchController.SearchBar;
			this.EdgesForExtendedLayout = UIRectEdge.None;

			this.search.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
			this.search.SpellCheckingType = UITextSpellCheckingType.No;
			this.search.BarStyle = UIBarStyle.Default;
			this.search.SearchBarStyle = UISearchBarStyle.Prominent;
			this.search.Placeholder = "Search...";

			this.search.CancelButtonClicked += (object sender, EventArgs e) =>
			{
				this.search.ResignFirstResponder();
			};
			this.search.TextChanged += (object sender, UISearchBarTextChangedEventArgs e) =>
			{
				SystemSound keyboardClick = new SystemSound(1105);
				keyboardClick.PlaySystemSound();
			};

			this.search.SearchButtonClicked += (object sender, EventArgs e) =>
			{
				search.ResignFirstResponder();
			};

			this.TableView.TableHeaderView = search;

			var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
			var directory = Directory.GetFiles(documents, "*.pdf");

			var fileName = Path.Combine(documents, "*.pdf");

			this.appDelegate.directories = directory;


			NSError error = new NSError();
			try
			{
				if (NSFileManager.DefaultManager.GetDirectoryContent(documents, out error).Length == 0)
				{
					throw new FileNotFoundException();
				}
				else {
					for (int i = 0; i <= directory.Length - 1; i++)
					{

						try
						{
							if (directory[i] == null)
							{
								throw new ArgumentOutOfRangeException();
							}
							else {
									this.pdfList.Add(Path.GetFileName(directory[i]));
									this.creationDate.Add(Convert.ToString(Directory.GetCreationTime(directory[i])));
									addImageContext(directory, i);	
							}
						}
						catch(ArgumentOutOfRangeException) {
							Console.WriteLine("File does not exist"); 
						}
					
					} 
				}
			}
			catch(FileNotFoundException) {
				Console.WriteLine("Cannot find the specified pdf file in the library"); 
			}

			if (this.pdfList.Count == 0)
			{
				emptyPDF = new UIView();

				emptyImage = new UIImageView();

				this.description = new UILabel();
				this.description.Text = "This page contains no PDFs. To get started adding your ";
				this.description.Font = UIFont.FromName("Georgia-Italic", 26.0f);
				this.description.AdjustsFontSizeToFitWidth = true;

				this.description_2 = new UILabel();
				this.description_2.Text = "own PDFs drag your files through iTunes file sharing";
				this.description_2.Font = UIFont.FromName("Georgia-Italic", 26.0f);
				this.description_2.AdjustsFontSizeToFitWidth = true;


				this.titleDescription = new UILabel();
				this.titleDescription.Text = "No PDFs";
				this.titleDescription.Font = UIFont.SystemFontOfSize(26.0f);
				this.titleDescription.Font = UIFont.FromName("AmericanTypewriter-Bold", 26.0f);

				if (UIApplication.SharedApplication.StatusBarHidden == true)
				{
					emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

					emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.Y - 200.0f, 200, 200);

					this.description.Frame = new CGRect(this.View.Bounds.Left + 35.0f, this.View.Center.Y + 10.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
					this.description_2.Frame = new CGRect(this.View.Bounds.Left + 35.0f, this.View.Center.Y + 70.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
					this.titleDescription.Frame = new CGRect(this.View.Center.X - 60.0f, this.View.Center.Y - 180.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
				}
				else
				{
					emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

					emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.X - 95.0f, 200, 200);

					this.description.Frame = new CGRect(this.View.Bounds.Left + 5.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
					this.description_2.Frame = new CGRect(this.View.Bounds.Left + 5.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
					this.titleDescription.Frame = new CGRect(this.View.Center.X - 60.0f, this.View.Center.Y - 240.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
				}

				emptyImage.Image = new UIImage("EmptyScreen.png");

				emptyPDF.AddSubview(emptyImage);
				emptyPDF.AddSubview(this.description);
				emptyPDF.AddSubview(this.description_2);
				emptyPDF.AddSubview(this.titleDescription);

				this.TableView.SeparatorColor = UIColor.GroupTableViewBackgroundColor;
				this.TableView.TintColor = UIColor.GroupTableViewBackgroundColor;
				this.TableView.TableHeaderView = null;

				this.Add(emptyPDF);
				this.View.BringSubviewToFront(emptyPDF);
			}
			else {
				this.TableView.SeparatorColor = UIColor.LightGray;
				this.TableView.TintColor = UIColor.LightGray;

				//this.TableView.TableHeaderView = this.search;
				emptyPDF = new UIView();

				emptyImage = new UIImageView();

				emptyPDF.RemoveFromSuperview();
				emptyImage.RemoveFromSuperview();
			}
			this.emptyPDF.BackgroundColor = UIColor.GroupTableViewBackgroundColor;


			UIBarButtonItem cancelEditing = new UIBarButtonItem(UIBarButtonSystemItem.Done, (sender, e) =>
			{
				this.selectedCellsToRemove.Clear();
				this.TableView.SetEditing(false, true);
				this.NavigationItem.SetRightBarButtonItem(this.appDelegate.editPassword, true);
			});

			//nav bar items
			UIBarButtonItem edit = new UIBarButtonItem(UIBarButtonSystemItem.Edit, (object sender, EventArgs e) =>
			{
				//pushes the password reader controller which allows the user to enter 
				var documents_2 = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
				var passwordDirectory_2 = Path.Combine(documents, "*.pdf");


				NSError error_2 = new NSError();
				if (NSFileManager.DefaultManager.GetDirectoryContent(passwordDirectory_2, out error_2).Length == 0)
				{
					UIAlertController emptyPasswords = UIAlertController.Create("Nothing to delete", "You have no passwords listed here to delete", UIAlertControllerStyle.Alert);

					UIAlertAction confirmed = UIAlertAction.Create("Ok", UIAlertActionStyle.Default, (UIAlertAction obj) =>
					{
						emptyPasswords.Dispose();
					});

					emptyPasswords.AddAction(confirmed);

					if (this.PresentedViewController == null)
					{
						this.PresentViewController(emptyPasswords, true, () =>
						{
							SystemSound soundError = new SystemSound(4095);
							soundError.PlaySystemSound();
						});
					}
					else {
						this.PresentedViewController.DismissViewController(true, () =>
						{
							this.PresentedViewController.Dispose();
							this.PresentViewController(emptyPasswords, true, () =>
							{
								SystemSound soundError = new SystemSound(4095);
								soundError.PlaySystemSound();
							});
						});
					}
				}
				else {
					this.TableView.SetEditing(true, true);
					this.NavigationItem.SetRightBarButtonItem(cancelEditing, true);
				}
			});

			this.appDelegate.editPassword = edit;


		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return this.pdfList.Count; 
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell pdfCell = new UITableViewCell(UITableViewCellStyle.Subtitle, "pdfCell");

			if(pdfCell == null) {
				pdfCell = new UITableViewCell(UITableViewCellStyle.Subtitle, "pdfCell");
			}

			pdfCell.TextLabel.Text = pdfList[indexPath.Row];
			pdfCell.TextLabel.TextColor = UIColor.Black;

			pdfCell.DetailTextLabel.Text = "Created on: " + creationDate[indexPath.Row]; 
			pdfCell.DetailTextLabel.TextColor = UIColor.LightGray;

			//pdfCell.Accessory = UITableViewCellAccessory.DisclosureIndicator;

			UIImageView screenShot = new UIImageView();
			screenShot.Frame = new CGRect(0, 20, 40, 40);
			screenShot.Image = this.thumbnailImage[indexPath.Row];

			pdfCell.AccessoryView = screenShot;

			return pdfCell; 
		}

		public void filteredContent(string searchedText)
		{
			this.appDelegate.newResults = this.pdfList.Where((arg) => arg.ToLower().Contains(searchedText.ToLower()) || arg.ToUpper().Contains(searchedText.ToUpper())).ToList();

			this.TableView.ReloadData();

			this.appDelegate.tableView.ReloadData();
		}

		private void corruptController(int index){
			var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
			var directory = Directory.GetFiles(documents, "*.pdf");

			UIAlertController corruptAlert = UIAlertController.Create("Corrupt file cannot be opened!","'" + Path.GetFileName(directory[index]) + "'" + " cannot be opened because it appears to be corrupt. Would you like to delete this file?", UIAlertControllerStyle.Alert);

			UIAlertAction confirmed = UIAlertAction.Create("No", UIAlertActionStyle.Destructive, (UIAlertAction obj) => {
				corruptAlert.Dispose();
			});

			UIAlertAction deleteFile = UIAlertAction.Create("Delete file", UIAlertActionStyle.Cancel, (UIAlertAction obj) => {
				File.Delete(directory[index]);
				this.pdfList.RemoveAt(index);
				this.creationDate.RemoveAt(index);
				this.thumbnailImage.RemoveAt(index);

				int indexCorrupt = this.pdfList.IndexOf(this.pdfList[index]);
				int indexOfficial = this.corruptIndex.IndexOf(indexCorrupt);

				this.corruptIndex.RemoveAt(indexOfficial);
				this.TableView.ReloadData();

			//	this.corruptIndex.Clear();


				//why do i need to call on view didload again in order to proces any other corrupt files with broken packets
			//	this.ViewDidLoad();
			});

			corruptAlert.AddAction(confirmed);
			corruptAlert.AddAction(deleteFile);

			if(this.PresentedViewController == null) {
				this.PresentViewController(corruptAlert, true, () =>
				{
					SystemSound sound = new SystemSound(4095);
					sound.PlaySystemSound();
				});
			}
			else {
				this.PresentedViewController.DismissViewController(true, () =>
				{
					this.PresentedViewController.Dispose();
					this.PresentViewController(corruptAlert, true, () =>{
						SystemSound sound = new SystemSound(4095);
						sound.PlaySystemSound();
					});
				});
			}
		}

		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			this.search.ResignFirstResponder();

			//has the user selected the cell
			if(this.corruptIndex.Contains(indexPath.Row) == true) {
				//replace the previous indices inside the corrupt index list with the new indices 
				corruptController(indexPath.Row);
			}

			UIStoryboard story = UIStoryboard.FromName("Main", NSBundle.MainBundle);
			//pushes the web view controller that loads the PDF 
			tableView.DeselectRow(indexPath, true);

			appDelegate.pdfString = tableView.CellAt(indexPath).TextLabel.Text; 

			try
			{
				PDFReader pdfControl = story.InstantiateViewController("PDFReader") as PDFReader;
				if (pdfControl == null)
				{
					throw new NullReferenceException();
				}
				else {
					this.NavigationController.PushViewController(pdfControl, true);
				}
			}
			catch (NullReferenceException)
			{
				Console.WriteLine("PDF Viewer");
			}
		}
	}

	public class searchUpdator : UISearchResultsUpdating
	{
		LibraryControllerTable search = new LibraryControllerTable();

		public searchUpdator(LibraryControllerTable searchValue)
		{
			search = searchValue;
		}

		public override void UpdateSearchResultsForSearchController(UISearchController searchController)
		{
			search.filteredContent(searchController.SearchBar.Text);
		}
	}

	public class resultsController : UITableViewController
	{

		public AppDelegate appDelegate
		{
			get
			{
				return (AppDelegate)UIApplication.SharedApplication.Delegate;
			}
		}

		//controller used to display results
		UISearchController search = new UISearchController();
		List<string> filteredResults = new List<string>() { "" };

		public resultsController() { }

		public resultsController(UISearchController searchController)
		{
			search = searchController;
		}

		public resultsController(UISearchController searchController, List<string> filteredResultsRef)
		{
			search = searchController;
			filteredResults = filteredResultsRef;
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return this.appDelegate.newResults.Count;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cellSearch = new UITableViewCell(UITableViewCellStyle.Value1, "SearchCell");

			if (cellSearch == null)
			{
				cellSearch = new UITableViewCell(UITableViewCellStyle.Value1, "SearchCell");
			}

			cellSearch.TextLabel.Text = this.appDelegate.newResults[indexPath.Row];
			cellSearch.TextLabel.TextColor = UIColor.Black;

			cellSearch.DetailTextLabel.Text = ">";
			cellSearch.DetailTextLabel.TextColor = UIColor.LightGray;

			return cellSearch;
		}

		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			//UIStoryboard story = UIStoryboard.FromName("Main", NSBundle.MainBundle);
			//pushes the web view controller that loads the PDF 
			this.appDelegate.tablePDFSearch = 1;
			this.DismissViewController(true, () =>
			{
				this.appDelegate.tablePDFSearch = 1;
				int indexRow = this.appDelegate.resultsStringPDF.IndexOf(tableView.CellAt(indexPath).TextLabel.Text);
				Console.WriteLine("Index to use: " + indexRow);
				this.appDelegate.selectedIndexPDF = NSIndexPath.FromRowSection(indexRow,0);

				//search cell has been selected
				this.appDelegate.searchedStringPDF = tableView.CellAt(indexPath).TextLabel.Text;
				this.appDelegate.library.ViewDidAppear(true);
			});

			tableView.DeselectRow(indexPath, true);
		}

		public override void ViewDidAppear(bool animated)
		{
			this.TableView.Frame = new CGRect(0, -40, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

			this.EdgesForExtendedLayout = UIRectEdge.None;

			this.TableView.ContentMode = UIViewContentMode.Top;

			this.appDelegate.tableView = this.TableView;

			this.TableView.ReloadData();

		}

		public override void ViewDidLoad()
		{
			this.EdgesForExtendedLayout = UIRectEdge.Top;
			this.TableView.ContentMode = UIViewContentMode.Top;
		}

		public override void TouchesEnded(NSSet touches, UIEvent evt)
		{
			if (evt.Type == UIEventType.Touches)
			{
				Console.WriteLine("Table view count: " + this.appDelegate.newResults.Count);
			}
		}
	}
}
