// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace SecurePDF
{
	public partial class VaultInstructionsController : UIViewController
	{
		public VaultInstructionsController (IntPtr handle) : base (handle)
		{
		}

		UIView emptyPDF = new UIView();
		UIImageView emptyImage = new UIImageView();
		UILabel description = new UILabel();
		UILabel description_2 = new UILabel();
		UILabel titleDescription = new UILabel();

		UINavigationBar navBar = new UINavigationBar();


		public VaultInstructionsController(){}

		public AppDelegate applicationDelegate {
			get {
				return (AppDelegate)UIApplication.SharedApplication.Delegate;
			}
		}

		public override bool ShouldAutorotate()
		{
			return false; 
		}

		public override UIInterfaceOrientation PreferredInterfaceOrientationForPresentation()
		{
			return UIInterfaceOrientation.Portrait; 
		}

		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations()
		{
			return UIInterfaceOrientationMask.Portrait;
		}

		public override void ViewWillLayoutSubviews()
		{
			if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeLeft || UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.LandscapeRight)
			{
				this.emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				this.emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.Y - 200.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Center.X - 315.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 50.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Center.X - 155.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 210.0f, 50.0f);

				this.titleDescription.Frame = new CGRect(this.View.Center.X - 70.0f, this.View.Center.Y - 180.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}
			else if (UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.Portrait || UIDevice.CurrentDevice.Orientation == UIDeviceOrientation.PortraitUpsideDown)
			{
				emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.X - 95.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Center.X - 190.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 50.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Center.X - 95.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 210.0f, 50.0f);
				this.titleDescription.Frame = new CGRect(this.View.Center.X - 70.0f, this.View.Center.Y - 240.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}
		}

		public override void ViewDidLoad()
		{
			emptyPDF = new UIView();

			emptyImage = new UIImageView();

			this.description = new UILabel();
			this.description.Text = "Welcome to iVault. Here you can store your photos, documents, and passwords,";
			this.description.Font = UIFont.FromName("Georgia-Italic", 26.0f);

			this.description_2 = new UILabel();
			this.description_2.Text = "and your data will be protected with the latest encryption standards";
			this.description_2.Font = UIFont.FromName("Georgia-Italic", 26.0f);

			this.description_2.AdjustsFontSizeToFitWidth = true;
			this.description.AdjustsFontSizeToFitWidth = true;

			this.titleDescription = new UILabel();
			this.titleDescription.Text = "iVault";
			this.titleDescription.Font = UIFont.SystemFontOfSize(26.0f);
			this.titleDescription.Font = UIFont.FromName("AmericanTypewriter-Bold", 26.0f);

			if (UIApplication.SharedApplication.StatusBarHidden == true)
			{
				emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.Y - 200.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Center.X - 315.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 15.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Center.X - 155.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);

				this.titleDescription.Frame = new CGRect(this.View.Center.X - 50.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}
			else
			{
				emptyPDF.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);

				emptyImage.Frame = new CGRect(emptyPDF.Center.X - 100.0f, emptyPDF.Center.X - 95.0f, 200, 200);

				this.description.Frame = new CGRect(this.View.Center.X - 190.0f, this.View.Center.Y, UIScreen.MainScreen.Bounds.Width - 15.0f, 50.0f);
				this.description_2.Frame = new CGRect(this.View.Center.X - 190.0f, this.View.Center.Y + 50.0f, UIScreen.MainScreen.Bounds.Width - 5.0f, 50.0f);
				this.titleDescription.Frame = new CGRect(this.View.Center.X - 50.0f, this.View.Center.Y - 150.0f, UIScreen.MainScreen.Bounds.Width - 50.0f, 300.0f);
			}

			emptyImage.Image = new UIImage("AppIcon.png");

			//emptyPDF.AddSubview(emptyImage);
			//emptyPDF.AddSubview(this.description);
			//emptyPDF.AddSubview(this.description_2);
			//emptyPDF.AddSubview(this.titleDescription);

			//this.View.Add(emptyPDF);
			//this.View.BringSubviewToFront(emptyPDF);


			UINavigationItem navItem = new UINavigationItem();
			navItem.Title = "Welcome to iVault";
			navItem.SetRightBarButtonItem(new UIBarButtonItem("Accept", UIBarButtonItemStyle.Done, (sender, e) =>
			{
				this.applicationDelegate.instructionsShared = 1;
				this.DismissViewController(true, () =>
				{
					this.Dispose();
				});
			}), true);

			this.navBar = new UINavigationBar();
			navBar.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, this.applicationDelegate.navBar_2.Bounds.Height + 30.0f);
			navBar.BarStyle = UIBarStyle.Default;
			navBar.BarTintColor = this.applicationDelegate.navBar_2.BarTintColor;
			navBar.BackgroundColor = this.applicationDelegate.navBar_2.BackgroundColor;
			navBar.Items = new UINavigationItem[] { navItem };

			this.Add(navBar);
		}
	}
}
